apiVersion: v1
kind: Secret
metadata:
  name: github-deployer-token
  namespace: codesageai
  labels:
    app.kubernetes.io/name: codesage-ai
    app.kubernetes.io/component: github-deployer
    app.kubernetes.io/part-of: codesage-ai
  annotations:
    kubernetes.io/service-account.name: github-deployer
type: kubernetes.io/service-account-token
