import { defineConfig, globalIgnores } from "eslint/config"
import nextVitals from "eslint-config-next/core-web-vitals"
import nextTs from "eslint-config-next/typescript"

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    // Playwright's dev server builds here so it can run alongside `pnpm dev`
    // (see next.config.ts). It is generated output, not source.
    ".next-e2e/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `msw init public/`. It ships its own eslint-disable
    // header, which this config then reports as unused.
    "public/mockServiceWorker.js",
  ]),
])

export default eslintConfig
