"""Alembic environment.

Reads the database URL from settings rather than alembic.ini so no credential is
committed, and imports every ORM module so ``--autogenerate`` sees the full model.

RLS note: policies and the non-superuser application role are *not* autogenerated
by Alembic. They live in hand-written migration bodies — see SRS DB-2 and the
TEAM TODO in SAD §9 that still owes the exact policy text.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from codesage_api.config import get_settings
from codesage_api.db.base import Base

# Importing the models package registers every table on Base.metadata.
import codesage_api.db.models  # noqa: F401

config = context.config

if config.config_file_name is not None:
    # disable_existing_loggers=False, and it is not optional.
    #
    # `fileConfig` defaults to True, which sets `disabled = True` on every logger
    # that already exists and is not named in alembic.ini. alembic.ini names
    # root, sqlalchemy and alembic. So every `codesage_api.*` logger already
    # imported goes silent for the rest of the process, and nothing says so.
    #
    # It cost us a CI failure nobody could reproduce: the integration tests run a
    # migration, that call silenced `codesage_api.services.auth`, and a later
    # test asserting a warning was logged saw nothing. Green on a laptop with no
    # Docker, red on CI, with the two events in different files.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

config.set_main_option("sqlalchemy.url", get_settings().migration_database_url)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
