"""Alembic environment.

Reads the database URL from settings rather than alembic.ini so no credential is
committed, and imports every ORM module so ``--autogenerate`` sees the full model.

RLS note: policies and the non-superuser application role are *not* autogenerated
by Alembic. They live in hand-written migration bodies — see SRS DB-2 and the
TEAM TODO in SAD §9 that still owes the exact policy text.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from codesage_api.config import get_settings
from codesage_api.db.base import Base

# Importing the models package registers every table on Base.metadata.
import codesage_api.db.models  # noqa: F401

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
