/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin sign-in
         * @description Redirects the browser to Asgardeo's authorization endpoint with a signed,
         *     single-use `state` value.
         *
         *     **This is a navigation, not a fetch.** The frontend renders it as
         *     `<a href="/api/auth/login">`, never as an XHR — the browser has to leave
         *     the page for the OIDC flow to work. It is the one endpoint a mock service
         *     worker cannot intercept.
         *
         *     The path carries no provider name: which identity provider the user picks
         *     is Asgardeo's business, not this API's.
         */
        get: operations["begin_sign_in"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OIDC redirect target
         * @description Asgardeo's redirect target. Validates `state`, exchanges the authorization
         *     code, and establishes a **server-side session**, returning its identifier
         *     in an httpOnly cookie. The browser never receives a token.
         *
         *     On first sign-in this also creates the user's Workspace, its Membership,
         *     and seeds the **Balanced** profile with `is_active = true` — so a workspace
         *     always has exactly one active profile and the read path never needs a
         *     fallback.
         *
         *     A `SecurityAuditRecord` is written for both success and failure (SEC-14).
         *     A failed sign-in has no established actor, which is exactly the event most
         *     worth recording.
         */
        get: operations["complete_sign_in"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who is signed in
         * @description Returns the signed-in user, or `401` if there is no valid session.
         *
         *     This is the only auth endpoint the client calls with `fetch`, and it is how
         *     the app decides whether to render the dashboard or bounce to sign-in.
         */
        get: operations["get_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the session
         * @description Deletes the session **server-side** and clears the cookie, so the session is
         *     invalid immediately (SEC-10).
         *
         *     This is why the session is server-side state rather than a self-contained
         *     JWT: a stateless token stays valid until it expires, and sign-out could not
         *     actually revoke it without a denylist — which is most of a session store
         *     anyway.
         */
        post: operations["sign_out"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List connected projects
         * @description Every repository connected to the caller's workspace. `latest_health` is a
         *     derived hint for the projects list and is absent until the project has at
         *     least one finalized snapshot.
         */
        get: operations["list_projects"];
        put?: never;
        /**
         * Connect a repository by URL
         * @description Validates the URL, reads the repository's metadata from GitHub, and records
         *     it against the workspace.
         *
         *     **v1.0 accepts public repositories only.** A private URL returns
         *     `REPOSITORY_NOT_PUBLIC` with a message that explains why rather than saying
         *     "forbidden" — a user pasting their own repository has done nothing wrong
         *     and needs to know that private support requires a GitHub App installation,
         *     which is not in this release.
         */
        post: operations["connect_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/branches": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
            };
            cookie?: never;
        };
        /**
         * Branches with head commit
         * @description Read from the GitHub REST API with ETag-conditional requests, so a repeated
         *     read usually costs no rate-limit quota.
         */
        get: operations["list_branches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
            };
            cookie?: never;
        };
        /**
         * The full dashboard payload
         * @description One response carrying all six dashboard outputs (SRS Appendix B): the health
         *     card, the category breakdown, the trend, the Refactor-First list, the data
         *     behind the finding detail, and the hotspot tree.
         *
         *     **Every score here is computed on this request** under the workspace's
         *     active profile — `health_score`, `grade`, `delta`, each finding's
         *     `priority`, each file's `debt_score`, and the whole trend line. None is read
         *     from a column (FR-21). A profile change therefore re-ranks everything with
         *     no re-scan, and the trend is redrawn end to end so every point is comparable
         *     with every other (FR-14, "one lens per line").
         *
         *     **There is no profile parameter, by design.** See the description at the top
         *     of this document.
         */
        get: operations["get_health_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
            };
            cookie?: never;
        };
        /**
         * Scan history
         * @description The stored snapshots for this repository, newest first (FR-19). Only
         *     successful scans appear — a cancelled or failed attempt is retained for
         *     diagnosis (SP-13) but is never presented as a result (DBR-22).
         *
         *     `finding_count` and `commit_sha` are stored facts; `health_score`, `grade`
         *     and `delta` are derived on this request, which is why switching profiles
         *     redraws this list too.
         */
        get: operations["list_scan_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a scan
         * @description Enqueues an analysis and returns immediately with `202` — the work runs on a
         *     Celery worker, never inside this request (PERF-05). The job is on the queue
         *     within one second (PERF-03).
         *
         *     **Skip-if-unchanged.** The API first reads the branch head SHA from GitHub
         *     and compares it with the SHA of the **last successful** scan of that branch.
         *     If they match, no job is queued and the response carries
         *     `phase: "done"` with the existing `scan_id`. Comparing against the last
         *     *successful* scan is what stops a cancelled attempt being mistaken for a
         *     stored snapshot.
         */
        post: operations["start_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/scan/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
                /**
                 * @description The analysis attempt's identifier, as returned by `POST …/scan`. Every
                 *     attempt has one, including attempts that end in `error` or `cancelled` —
                 *     only successful ones go on to produce a snapshot.
                 */
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        /**
         * Poll a scan
         * @description Polled once per second while a scan is active, and stopped as soon as
         *     `phase` is `done`, `error` or `cancelled` (SRS Table 3.107). No WebSockets
         *     and no Server-Sent Events in v1.0.
         *
         *     **The two fields come from two different stores.** `phase` is read from
         *     PostgreSQL and `progress` from Redis. Losing a percentage when the broker
         *     restarts costs nothing — the next poll produces a new one. Losing the fact
         *     that a scan failed would breach SP-13, which requires the terminal phase and
         *     its error message to be recoverable from the database alone.
         */
        get: operations["get_scan_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos/{repo_id}/scan/{scan_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
                /**
                 * @description The analysis attempt's identifier, as returned by `POST …/scan`. Every
                 *     attempt has one, including attempts that end in `error` or `cancelled` —
                 *     only successful ones go on to produce a snapshot.
                 */
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a running scan
         * @description **Cancellation is cooperative, not forced.** This sets a flag in Redis and
         *     returns immediately; it does not kill the worker. The worker reads the flag
         *     **between pipeline stages**, stops at the first boundary it reaches, deletes
         *     its clone and writes `phase: "cancelled"`.
         *
         *     Consequences worth knowing:
         *
         *     - The response is `202`, and `phase` is usually still `running`. The client
         *       learns the scan really stopped from the **next poll**, not from this call.
         *     - A user who presses Stop waits until the current stage ends. That is the
         *       price of never leaving a half-written snapshot.
         *     - Once finalization begins the scan completes. FR-6 requires the previous
         *       snapshot to survive a cancellation intact, and a killed write would leave
         *       a partial one.
         *     - The terminal phase is `cancelled`, **not** `idle`, so a scan that was
         *       stopped stays distinguishable from one that never ran.
         */
        post: operations["stop_scan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Available profiles
         * @description The three presets — **Balanced** (the workspace default), **Security-first**
         *     and **Delivery-speed** — plus any custom profile. Selecting a preset seeds
         *     the sliders in one interaction; adjusting from it is optional.
         */
        get: operations["list_profiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The active profile
         * @description The profile currently in force for the workspace. The Profiles screen reads
         *     this on load, so the sliders always open showing what is really applied
         *     rather than a client-side guess.
         */
        get: operations["get_active_profile"];
        /**
         * Apply a profile
         * @description Replaces the workspace's active profile with exactly the submitted values.
         *
         *     **PUT, not PATCH.** The body carries the **complete** profile — six numbers,
         *     never a delta. That makes the write idempotent, so retrying after a dropped
         *     response cannot leave a half-applied profile. It matters here specifically
         *     because the client fires a dependent read (`GET …/health`) immediately
         *     afterwards, and a half-applied profile would render a dashboard matching no
         *     profile the system actually holds.
         *
         *     **Nothing is sent while the user drags.** Slider positions are client state
         *     until **Apply** is pressed. A single drag crosses many intermediate values;
         *     writing each one would put a write and a full re-derivation on the server
         *     per pixel of travel, and would leave the user no way to abandon an
         *     experiment.
         *
         *     **Out-of-range weights are clamped, not rejected.** A weight of `9.0` is
         *     stored as `3.0` and returned as `3.0` with `200` — the response is the
         *     profile as it is *really in force*, which is what lets the client confirm
         *     what was saved instead of trusting what it sent. A **malformed** body (wrong
         *     type, missing key, unknown category) is a different thing and returns `422`.
         *
         *     **The same row is updated every time; profiles are not versioned.** Applying
         *     a profile overwrites the workspace's single `SCORING_PROFILE` row in place —
         *     its `id` never changes and no history is kept. There is deliberately no
         *     version column: no endpoint in this contract can express or return one, so
         *     accumulating a row per Apply would grow the table without bound for a
         *     history nothing is able to read. Scores are derived on read (FR-21), so a
         *     superseded profile also explains no stored result.
         *
         *     **This writes no snapshot and starts no scan.** Six numbers change on that
         *     one row, in one transaction. No
         *     `FINDING`, no `SNAPSHOT`, no `ANALYSIS_ATTEMPT` row is touched. A snapshot is
         *     keyed by commit SHA and records what the code was; a profile is not a commit.
         *     Were a profile change to write one, the trend chart would show a step on a
         *     day nobody touched the code (FR-21).
         *
         *     **The visibility floor holds regardless** (FR-24). No weight, including the
         *     minimum `0.1` on `security`, can push a critical security finding out of
         *     sight — such findings come back with `pinned_by_floor: true`.
         */
        put: operations["apply_profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Container orchestration only. Does not touch the database.
         */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Every non-2xx response in this API has this shape.
         *
         *     **Clients switch on `code`, never on `detail`.** `detail` is a human
         *     sentence whose wording may change; `code` is a stable constant. Per SEC-16,
         *     `detail` never carries a stack trace, SQL, an internal hostname or any other
         *     implementation detail.
         */
        Error: {
            /**
             * @description A human-readable sentence naming what failed.
             * @example A scan is already running for this branch.
             */
            detail: string;
            code: components["schemas"]["ErrorCode"];
            /** @description Field-level detail. Present on validation failures only. */
            errors?: {
                /**
                 * @description Dotted path to the offending field.
                 * @example weights.security
                 */
                field: string;
                detail: string;
            }[];
        };
        /**
         * @description The stable, machine-readable reason. New members may be added; existing
         *     members never change meaning.
         * @enum {string}
         */
        ErrorCode: "NOT_AUTHENTICATED" | "FORBIDDEN" | "NOT_FOUND" | "INVALID_REPOSITORY_URL" | "REPOSITORY_NOT_PUBLIC" | "REPOSITORY_UNREACHABLE" | "ALREADY_CONNECTED" | "SCAN_ALREADY_RUNNING" | "SCAN_NOT_CANCELLABLE" | "VALIDATION_FAILED" | "RATE_LIMITED" | "UPSTREAM_UNAVAILABLE" | "INTERNAL_ERROR";
        /**
         * @description How bad a finding is. **Assigned once, at detection, and never recomputed**
         *     (FR-8.1): the rule register fixes it for rule findings, the SATD marker
         *     table for SATD findings, and ML-2 assigns none because it produces no
         *     findings. No model and no user ever sets a severity.
         *
         *     Read by exactly two consumers — the base-point lookup in scoring, and the
         *     badge colour in the UI — so the ranking and the badge cannot disagree.
         * @enum {string}
         */
        Severity: "critical" | "high" | "medium" | "low";
        /**
         * @description Which detector produced the finding. **Exactly two values** (FR-8.2).
         *
         *     There is no `security` source: security patterns run inside the rule engine,
         *     so a security finding is a `rule` finding whose `category` is `security`. A
         *     separate source value would correlate perfectly with the category axis and
         *     collapse two orthogonal axes into one.
         *
         *     There is no `ml-risk` source either: ML-2 emits no findings at all, only a
         *     per-file risk score.
         * @enum {string}
         */
        Source: "rule" | "satd";
        /**
         * @description What kind of debt it is. **Exactly five values** (FR-9.3), orthogonal to
         *     `source` — a finding is always both *found by X* and *of type Y*.
         *
         *     Four are SATDAUG comment-dataset labels, so ML-1 trains and predicts on the
         *     same vocabulary the product uses. `security` is the fifth and is **never
         *     predicted** — it is emitted by the rule engine alone.
         *
         *     There is no `defect`: SATDAUG carries no `defect_debt` label, so it cannot
         *     be predicted and does not exist in the product.
         * @enum {string}
         */
        Category: "code-design" | "requirement" | "documentation" | "test" | "security";
        /**
         * @description A ≥ 85 · B ≥ 70 · C ≥ 55 · D ≥ 40 · E < 40.
         * @enum {string}
         */
        Grade: "A" | "B" | "C" | "D" | "E";
        /**
         * @description v1.0 is view-only: every finding is `open`. The later values exist now
         *     because FR-11 sums *open* finding priorities — the filter needs something to
         *     filter on. The v1.1 accept / resolve / false-positive actions will set them.
         * @enum {string}
         */
        FindingStatus: "open" | "accepted" | "resolved" | "false-positive";
        /**
         * @description `idle → queued → running → done | error | cancelled`.
         *
         *     `idle` is the resting state of the scan control **before** a scan; it is
         *     never a stored outcome. `cancelled` is a distinct terminal phase, not a
         *     return to `idle`, so a scan that was stopped stays distinguishable from one
         *     that never ran — which SP-13 needs for diagnosis and DBR-22 needs to keep a
         *     cancelled attempt from ever being presented as a result.
         * @enum {string}
         */
        ScanPhase: "idle" | "queued" | "running" | "done" | "error" | "cancelled";
        /**
         * @description The signed-in user. Carries no token and no provider credential — those stay
         *     server-side (SEC-09).
         *
         *     **Only the two identifiers are guaranteed.** `user_id` and `workspace_id`
         *     are ours and always exist. Everything else is display detail supplied by
         *     the identity provider, and a provider may simply not have it: a GitHub
         *     account can keep its email private and need never set a display name.
         *
         *     Since the application's identity is the Asgardeo subject and nothing else,
         *     a missing display name must not be able to fail a sign-in that otherwise
         *     succeeded. Clients render a fallback — the email, or initials, or a generic
         *     avatar — rather than assuming these are present.
         */
        Session: {
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email?: string | null;
            name?: string | null;
            /** Format: uri */
            avatar_url?: string | null;
            /**
             * Format: uuid
             * @description The tenant every request is scoped to.
             */
            workspace_id: string;
            /**
             * @description Which provider the user authenticated with inside Asgardeo — `github`,
             *     `google` or `local`. Display only; the application's identity is the
             *     Asgardeo subject, not this.
             * @example github
             */
            identity_provider?: string | null;
        };
        ConnectRepoRequest: {
            /**
             * Format: uri
             * @description A public repository URL.
             * @example https://github.com/octocat/Hello-World
             */
            url: string;
        };
        Repo: {
            /** Format: uuid */
            id: string;
            /** @example Hello-World */
            name: string;
            /** @example octocat */
            owner: string;
            /**
             * @description Recorded for every repository from v1.0 - FR-3 stores it and the projects
             *     list displays it. What is deferred is *connecting* a private repository,
             *     which needs a GitHub App installation and the SEC-04/SEC-06 authorization
             *     controls: that is **v2**, not v1.1.
             * @enum {string}
             */
            visibility: "public" | "private";
            /** Format: uri */
            url: string;
            /** @example main */
            default_branch: string;
            /** Format: date-time */
            connected_at: string;
            /**
             * @description A derived hint for the projects list. **Absent** until the project has
             *     at least one successful scan — absent means "not yet scanned", which is
             *     a different thing from a health score of zero.
             */
            latest_health?: components["schemas"]["LatestHealth"] | null;
        };
        LatestHealth: {
            score: number;
            grade: components["schemas"]["Grade"];
            /** @description Change since the previous snapshot, both scored under the active profile. */
            delta: number;
        };
        Branch: {
            /** @example main */
            name: string;
            is_default: boolean;
            /**
             * @description Full 40-character SHA. The UI shows the first seven.
             * @example 9fceb02d0ae598e95dc970b74767f19372d61af8
             */
            head_commit_sha?: string | null;
            /** Format: date-time */
            head_commit_at?: string | null;
        };
        StartScanRequest: {
            /** @example main */
            branch: string;
        };
        /**
         * @description The scan-button state machine. `phase` comes from PostgreSQL and `progress`
         *     from Redis — see `GET …/scan/{scan_id}` for why they live in different
         *     stores.
         */
        ScanStatus: {
            /** Format: uuid */
            scan_id: string;
            phase: components["schemas"]["ScanPhase"];
            /** @description Meaningful while `phase` is `running`; otherwise 0 or 100. */
            progress: number;
            branch?: string | null;
            /** @description The commit this scan is analysing. */
            commit_sha?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /**
             * @description Present only when `phase` is `error`. Stored on the attempt row, not
             *     merely logged, so a user-reported failure is diagnosable from the
             *     database alone (SP-13).
             */
            error?: string | null;
        };
        /** @description One row in the Scan-History view (FR-19). */
        ScanSummary: {
            /**
             * Format: uuid
             * @description Pass to `GET …/health?snapshot_id=` to load it into the dashboard.
             */
            snapshot_id: string;
            /**
             * Format: uuid
             * @description The analysis attempt that produced this snapshot.
             */
            scan_id: string;
            branch: string;
            commit_sha: string;
            /** Format: date-time */
            scanned_at: string;
            /** @description Stored fact. */
            finding_count: number;
            /** @description Derived on this request. */
            health_score: number;
            grade: components["schemas"]["Grade"];
            /** @description Versus the previous snapshot, both under the active profile. */
            delta: number;
        };
        /**
         * @description One row in the Refactor-First list, and the subject of the finding-detail
         *     panel. The atomic unit of output.
         *
         *     `severity` and `category` are **stored facts** written at detection.
         *     `priority` is **derived** on this request under the active profile — it is
         *     included as the sort key the list is already ordered by, so the client never
         *     re-sorts and the badge can never disagree with the ranking.
         */
        Finding: {
            /**
             * @description Stable across scans, so a finding can be tracked over time and
             *     deduplicated (DBR-15).
             */
            fingerprint: string;
            source: components["schemas"]["Source"];
            category: components["schemas"]["Category"];
            severity: components["schemas"]["Severity"];
            /** @example src/main/java/com/acme/Billing.java */
            file: string;
            line: number;
            /**
             * @description The method or class the finding sits on. Null for file-scoped rules.
             * @example charge
             */
            symbol?: string | null;
            /**
             * @description A one-line, plain-English explanation produced by a **string template**,
             *     never by text generation (FR-16). Reliable, instant, and incapable of
             *     hallucinating.
             * @example charge() has cyclomatic complexity 18, over the limit of 15 - split it into smaller functions.
             */
            reason: string;
            status: components["schemas"]["FindingStatus"];
            /**
             * @description `base_points(severity) × category_weight × source_trust × churn_factor ×
             *     risk_factor` (FR-11). Derived, never stored. The list is returned already
             *     sorted by this, descending.
             */
            priority: number;
            /**
             * @description True when this finding is held in the visible list by the
             *     **critical-security visibility floor** (FR-24) rather than by its
             *     computed priority. Lets the UI explain why a row is present even at the
             *     minimum `security` weight of 0.1.
             * @default false
             */
            pinned_by_floor: boolean;
            /**
             * @description Which rule fired. Rule findings only.
             * @example complex-function
             */
            rule_id?: string | null;
            /**
             * @description The measured value. Rule findings only.
             * @example 18
             */
            metric_value?: number | null;
            /**
             * @description The limit crossed. Rule findings only.
             * @example 15
             */
            threshold?: number | null;
            /**
             * @description The developer's own words, quoted as evidence. SATD findings only. Only
             *     the comment that produced the finding is stored — never the surrounding
             *     source (DBR-27).
             * @example // FIXME: this is not thread-safe
             */
            comment_text?: string | null;
            /** @description ML-1's confidence in the predicted category. SATD findings only. */
            confidence?: number | null;
        };
        /** @description Per-file numbers behind the heat map and the hotspot ranking. */
        FileScore: {
            file: string;
            /** @description Σ of the priorities of the open findings in this file. Derived. */
            debt_score: number;
            /**
             * @description ML-2's bug-proneness estimate — a **stored fact**, not derived.
             *
             *     **`null` means the ML service was unreachable** when this snapshot was
             *     taken, so no estimate exists. That is different from `0.0`, which is a
             *     measured "this file looks safe". Render `null` as "not assessed" and
             *     never as a zero-risk badge.
             *
             *     A risky file with no findings still contributes no debt: risk enters
             *     scoring only as a bounded multiplier on findings that already exist
             *     (FR-10).
             */
            risk_score: number | null;
        };
        /**
         * @description A node in the hotspot file tree (FR-18). Folder values aggregate the stored
         *     file scores beneath them, so drilling in re-aggregates a subtree by summing
         *     numbers already in memory — no re-scan and no second query.
         */
        TreeNode: {
            /** @example src/main/java/com/acme */
            path: string;
            /** @example acme */
            name: string;
            /** @enum {string} */
            type: "file" | "folder";
            /** @description Drives the red → amber → green tint. */
            health_score: number;
            grade: components["schemas"]["Grade"];
            debt_score: number;
            /** @description Files only, and null when unassessed. See `FileScore.risk_score`. */
            risk_score?: number | null;
            /** @description Folders only. */
            children?: components["schemas"]["TreeNode"][] | null;
        };
        /**
         * @description One point on the trend chart (FR-14). **Every point on a line is computed
         *     under the same, currently active profile**, so a profile change redraws the
         *     entire history and every point stays comparable with every other. A line
         *     whose points came from different profiles would be unreadable: you could not
         *     tell a code change from a settings change.
         */
        HealthPoint: {
            /** Format: date-time */
            t: string;
            score: number;
            commit_sha?: string | null;
        };
        /**
         * @description One slice of the category pie (FR-13). `count` is a plain query over stored
         *     rows; `debt` is weighted by the active profile — so the two move
         *     independently, and a category can hold many findings but little debt.
         */
        CategoryBreakdownItem: {
            category: components["schemas"]["Category"];
            count: number;
            debt: number;
        };
        /**
         * @description The whole dashboard in one response — all six outputs of SRS Appendix B.
         *
         *     Everything numeric here is derived on this request under the active profile.
         *     The client renders; it computes nothing.
         */
        HealthReport: {
            /** Format: uuid */
            snapshot_id: string;
            /** Format: uuid */
            repo_id: string;
            branch: string;
            /** @description The commit analysed. The UI shows the first seven characters. */
            commit_sha: string;
            /** Format: date-time */
            scanned_at: string;
            health_score: number;
            grade: components["schemas"]["Grade"];
            /**
             * @description Versus the previous snapshot, **both scored under the same active
             *     profile** — so it always reflects a change in the code, never a change
             *     in settings.
             */
            delta: number;
            /** @description Critical + high, for the health-card summary. */
            red_issue_count: number;
            /**
             * @description The active profile's name, shown on the trend chart. Without the label,
             *     the chart changing shape after a profile switch reads as a defect
             *     (FR-14).
             * @example Balanced
             */
            profile: string;
            /**
             * @description The ML model version that produced this snapshot (AI-03, DBR-18). Null
             *     when the snapshot was taken in degraded mode with no ML available.
             */
            model_version?: string | null;
            history: components["schemas"]["HealthPoint"][];
            tree: components["schemas"]["TreeNode"][];
            file_scores: components["schemas"]["FileScore"][];
            /** @description The Refactor-First list, already sorted by `priority` descending. */
            findings: components["schemas"]["Finding"][];
            category_breakdown: components["schemas"]["CategoryBreakdownItem"][];
        };
        /**
         * @description One weight per `Category` value — five, no more and no fewer. Modelled as
         *     named fields rather than a free-form map so that a client omitting one, or
         *     inventing a sixth, is rejected at the edge instead of producing a missing-key
         *     failure deep inside the scoring engine.
         *
         *     Bounds are documented here, but **the server is the enforcement point**: it
         *     clamps on write and returns what it stored. The client-side clamp is a
         *     usability affordance, not the rule.
         */
        CategoryWeights: {
            /** @default 1 */
            security: number;
            /** @default 1 */
            code_design: number;
            /** @default 1 */
            requirement: number;
            /** @default 1 */
            documentation: number;
            /** @default 1 */
            test: number;
        };
        /**
         * @description The complete profile — six numbers. Never a delta; that is what makes the
         *     `PUT` idempotent.
         */
        ApplyProfileRequest: {
            /**
             * @description Optional label. Sending a preset's name records which preset the values
             *     came from; omit it for a custom profile.
             */
            name?: string | null;
            weights: components["schemas"]["CategoryWeights"];
            /**
             * @description The trust slider `s`. `0` = trust the model, `1` = trust the rules.
             *     Scoring derives `rule_trust = 0.5 + s` and `ml_trust = 1.5 − s` from it
             *     (FR-11).
             *
             *     **Security findings are excluded**: `source_trust` is fixed at 1.0 for
             *     the `security` category, so no position of this slider can de-weight
             *     them (FR-24 mechanism 2).
             * @default 0.5
             */
            trust_s: number;
        };
        /** @description A stored profile, as returned after clamping. */
        ScoreProfile: {
            /** Format: uuid */
            id: string;
            /** @example Balanced */
            name: string;
            weights: components["schemas"]["CategoryWeights"];
            trust_s: number;
            /** @description Presets are read-only templates that seed the sliders. */
            is_preset: boolean;
            /**
             * @description Whether this is the workspace's active profile. Stored as `is_active` on
             *     the profile row, under a partial unique index on `(workspace_id) WHERE
             *     is_active` — so "at most one active profile per workspace" is refused by
             *     the database on write rather than being a rule a handler must remember
             *     (locked decision 11).
             *
             *     The index guarantees *at most* one. That a workspace always has *at
             *     least* one is guaranteed separately, by sign-in seeding **Balanced** as
             *     active when the workspace is created. `PUT /api/profiles/active` must
             *     therefore clear the old row and set the new one in a single transaction;
             *     a clear that can commit on its own would leave a workspace with no
             *     active profile.
             */
            is_active: boolean;
        };
    };
    responses: {
        /** @description No valid session. The client should redirect to `/api/auth/login`. */
        NotAuthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "Sign in to continue.",
                 *       "code": "NOT_AUTHENTICATED"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The resource belongs to another workspace. Row-Level Security keys every
         *     tenant-owned table on `workspace_id` (DBR-3), so this is enforced in the
         *     database rather than only in application code.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "You do not have access to that resource.",
                 *       "code": "FORBIDDEN"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such resource in this workspace. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "Not found.",
                 *       "code": "NOT_FOUND"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description The request body is malformed — a wrong type, a missing key, or an unknown
         *     category. Distinct from an out-of-range weight, which is clamped and
         *     accepted rather than refused.
         */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "The request could not be processed.",
                 *       "code": "VALIDATION_FAILED",
                 *       "errors": [
                 *         {
                 *           "field": "weights.security",
                 *           "detail": "Input should be a valid number."
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests (SEC-12). */
        RateLimited: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "Too many requests. Try again shortly.",
                 *       "code": "RATE_LIMITED"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description A required external service — GitHub or Asgardeo — is unavailable or
         *     degraded (REL-06, PERF-09). Previously completed results stay readable.
         */
        UpstreamUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "An external service is temporarily unavailable.",
                 *       "code": "UPSTREAM_UNAVAILABLE"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The connected repository's identifier. */
        RepoId: string;
        /**
         * @description The analysis attempt's identifier, as returned by `POST …/scan`. Every
         *     attempt has one, including attempts that end in `error` or `cancelled` —
         *     only successful ones go on to produce a snapshot.
         */
        ScanId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    begin_sign_in: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the Asgardeo authorization endpoint. */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    complete_sign_in: {
        parameters: {
            query: {
                /** @description Authorization code issued by Asgardeo. */
                code: string;
                /**
                 * @description The single-use nonce issued at `/api/auth/login`. Without checking it,
                 *     the callback would accept an authorization code from anywhere, which
                 *     is CSRF on the sign-in flow.
                 */
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Session established. Redirects to the Projects page. Sets the session
             *     cookie with `HttpOnly`, `Secure`, `SameSite=Lax`.
             */
            302: {
                headers: {
                    Location?: string;
                    /** @example codesage_session=…; HttpOnly; Secure; SameSite=Lax; Path=/ */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description The `state` did not validate, or the code exchange failed. Redirects to
             *     the login page with an error rather than rendering a JSON body — the
             *     caller here is a browser mid-navigation, not a script.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    get_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["NotAuthenticated"];
        };
    };
    sign_out: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. The cookie is cleared. */
            204: {
                headers: {
                    /** @example codesage_session=; Max-Age=0; Path=/ */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NotAuthenticated"];
        };
    };
    list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The connected projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repo"][];
                };
            };
            401: components["responses"]["NotAuthenticated"];
        };
    };
    connect_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRepoRequest"];
            };
        };
        responses: {
            /** @description Connected. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repo"];
                };
            };
            /**
             * @description The URL is malformed, the repository is unreachable, or it is private.
             *     Distinguish the three by `code`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["NotAuthenticated"];
            /** @description Already connected to this workspace. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    list_branches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The repository's branches. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Branch"][];
                };
            };
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            503: components["responses"]["UpstreamUnavailable"];
        };
    };
    get_health_report: {
        parameters: {
            query: {
                /**
                 * @description Branch name. Trends and deltas are per branch.
                 * @example main
                 */
                branch: string;
                /**
                 * @description Load a specific historical snapshot instead of the newest one (FR-19).
                 *     Omit for the latest. Only snapshots produced by a **successful** scan
                 *     are addressable — a cancelled or failed attempt produces no snapshot.
                 */
                snapshot_id?: string;
            };
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The dashboard payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["Forbidden"];
            /**
             * @description No repository, no such branch, or the branch has never been scanned
             *     successfully. The client renders the empty state, not an error.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    list_scan_history: {
        parameters: {
            query?: {
                /** @description Restrict to one branch. Omit for all branches. */
                branch?: string;
            };
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot summaries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanSummary"][];
                };
            };
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    start_scan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartScanRequest"];
            };
        };
        responses: {
            /**
             * @description Queued, or skipped as unchanged. Poll `GET /api/repos/{repo_id}/scan/{scan_id}`
             *     once per second until `phase` is terminal.
             */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanStatus"];
                };
            };
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description A scan is already running for this branch. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "A scan is already running for this branch.",
                     *       "code": "SCAN_ALREADY_RUNNING"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    get_scan_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
                /**
                 * @description The analysis attempt's identifier, as returned by `POST …/scan`. Every
                 *     attempt has one, including attempts that end in `error` or `cancelled` —
                 *     only successful ones go on to produce a snapshot.
                 */
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current phase and progress. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanStatus"];
                };
            };
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    stop_scan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The connected repository's identifier. */
                repo_id: components["parameters"]["RepoId"];
                /**
                 * @description The analysis attempt's identifier, as returned by `POST …/scan`. Every
                 *     attempt has one, including attempts that end in `error` or `cancelled` —
                 *     only successful ones go on to produce a snapshot.
                 */
                scan_id: components["parameters"]["ScanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested. Keep polling until `phase` becomes `cancelled`. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanStatus"];
                };
            };
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description The scan already reached a terminal phase, or finalization has begun and
             *     is past the last cancellation checkpoint.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "This scan can no longer be cancelled.",
                     *       "code": "SCAN_NOT_CANCELLABLE"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    list_profiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The available profiles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreProfile"][];
                };
            };
            401: components["responses"]["NotAuthenticated"];
        };
    };
    get_active_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreProfile"];
                };
            };
            401: components["responses"]["NotAuthenticated"];
        };
    };
    apply_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyProfileRequest"];
            };
        };
        responses: {
            /**
             * @description The profile **as stored**, after clamping. Compare it with what you sent:
             *     a differing value means it was out of range.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreProfile"];
                };
            };
            401: components["responses"]["NotAuthenticated"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
}
