"""add owner and created_at to repository

Revision ID: 3f1b84f5211f
Revises: 20260812_0001
Create Date: 2026-08-20 10:49:05.650664
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3f1b84f5211f'
down_revision: Union[str, None] = '20260812_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_session_user_id_app_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_session_workspace_id_workspace'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    op.create_index(op.f('ix_session_user_id'), 'session', ['user_id'], unique=False)
    op.create_index(op.f('ix_session_workspace_id'), 'session', ['workspace_id'], unique=False)
    op.add_column('app_user', sa.Column('asgardeo_sub', sa.String(length=255), nullable=False))
    op.add_column('app_user', sa.Column('email', sa.String(length=320), nullable=True))
    op.add_column('app_user', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('app_user', sa.Column('avatar_url', sa.String(length=1000), nullable=True))
    op.add_column('app_user', sa.Column('identity_provider', sa.String(length=50), nullable=True))
    op.alter_column('app_user', 'github_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('app_user', 'github_username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_app_user_github_user_id'), table_name='app_user')
    op.create_index(op.f('ix_app_user_asgardeo_sub'), 'app_user', ['asgardeo_sub'], unique=True)
    op.add_column('repository', sa.Column('owner', sa.String(length=255), nullable=False))
    op.add_column('repository', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('scoring_preset', sa.Column('security_weight', sa.Double(), nullable=False))
    op.drop_column('scoring_preset', 'defect_weight')
    op.add_column('scoring_profile', sa.Column('documentation_weight', sa.Double(), nullable=False))
    op.drop_constraint(op.f('uq_scoring_profile_workspace_id_name_version'), 'scoring_profile', type_='unique')
    op.create_unique_constraint(op.f('uq_scoring_profile_workspace_id_name'), 'scoring_profile', ['workspace_id', 'name'])
    op.drop_column('scoring_profile', 'document_weight')
    op.drop_column('scoring_profile', 'version')
    op.drop_column('scoring_profile', 'defect_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoring_profile', sa.Column('defect_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('scoring_profile', sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('scoring_profile', sa.Column('document_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_scoring_profile_workspace_id_name'), 'scoring_profile', type_='unique')
    op.create_unique_constraint(op.f('uq_scoring_profile_workspace_id_name_version'), 'scoring_profile', ['workspace_id', 'name', 'version'], postgresql_nulls_not_distinct=False)
    op.drop_column('scoring_profile', 'documentation_weight')
    op.add_column('scoring_preset', sa.Column('defect_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('scoring_preset', 'security_weight')
    op.drop_column('repository', 'created_at')
    op.drop_column('repository', 'owner')
    op.drop_index(op.f('ix_app_user_asgardeo_sub'), table_name='app_user')
    op.create_index(op.f('ix_app_user_github_user_id'), 'app_user', ['github_user_id'], unique=True)
    op.alter_column('app_user', 'github_username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('app_user', 'github_user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('app_user', 'identity_provider')
    op.drop_column('app_user', 'avatar_url')
    op.drop_column('app_user', 'display_name')
    op.drop_column('app_user', 'email')
    op.drop_column('app_user', 'asgardeo_sub')
    op.drop_index(op.f('ix_session_workspace_id'), table_name='session')
    op.drop_index(op.f('ix_session_user_id'), table_name='session')
    op.drop_table('session')
    # ### end Alembic commands ###
