"""remove repository test note

Revision ID: 66c10bdd2b49
Revises: feb0a6dc33ca
Create Date: 2026-08-20 10:58:04.327988
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66c10bdd2b49'
down_revision: Union[str, None] = 'feb0a6dc33ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'test_note')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('test_note', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
