"""add commits 90d to process metric

Revision ID: 7dd2f16f52c8
Revises: 20260820_0001
Create Date: 2026-08-24 16:46:33.575099
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7dd2f16f52c8'
down_revision: str | None = '20260820_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_metric', sa.Column('commits_90d', sa.Integer(), nullable=False))
    op.drop_column('process_metric', 'churn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_metric', sa.Column('churn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('process_metric', 'commits_90d')
    # ### end Alembic commands ###
