"""add repository test note

Revision ID: feb0a6dc33ca
Revises: 3f1b84f5211f
Create Date: 2026-08-20 10:56:15.783352
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'feb0a6dc33ca'
down_revision: Union[str, None] = '3f1b84f5211f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('test_note', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'test_note')
    # ### end Alembic commands ###
